
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PALAVRA_CHAVE = 2;
  public static final int RBRACE = 12;
  public static final int RPAREN = 14;
  public static final int SEMI = 15;
  public static final int NUMERO_REAL = 6;
  public static final int LPAREN = 13;
  public static final int COLON = 16;
  public static final int LBRACE = 11;
  public static final int TIPO = 3;
  public static final int ATRIBUICAO = 8;
  public static final int EOF = 0;
  public static final int TEXTO = 7;
  public static final int error = 1;
  public static final int NUMERO_INT = 5;
  public static final int IDENTIFICADOR = 4;
  public static final int OP_LOGICO = 9;
  public static final int ERRO = 17;
  public static final int OP_MATEMATICO = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PALAVRA_CHAVE",
  "TIPO",
  "IDENTIFICADOR",
  "NUMERO_INT",
  "NUMERO_REAL",
  "TEXTO",
  "ATRIBUICAO",
  "OP_LOGICO",
  "OP_MATEMATICO",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "COLON",
  "ERRO"
  };
}

